-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 09, 2018 at 11:12 AM
-- Server version: 10.1.37-MariaDB
-- PHP Version: 7.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `grupp4`
--

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `ArticleID` int(11) NOT NULL,
  `ArticleImage` varchar(255) DEFAULT NULL,
  `ArticleTitle` varchar(255) DEFAULT NULL,
  `ArticleText` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`ArticleID`, `ArticleImage`, `ArticleTitle`, `ArticleText`) VALUES
(1, 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'No iuvaret reprimique nec', 'Quo mutat error graeci et, his ex dicam eligendi, tale scaevola petentium ius eu. Utroque persequeris id vim. No movet alienum incorrupte eam, noster philosophia et vim. Alia natum per ei, sed minim eligendi quaerendum te, mei an molestie mnesarchum. Id ius dictas voluptua dignissim, ignota postea recusabo sed an. Nam meliore gloriatur eu.\r\n\r\nDebitis accusamus adversarium ea cum, nibh partiendo percipitur ea cum, sea id iudicabit urbanitas expetendis. Vix eu prima reprimique conclusionemque, nam te nihil incorrupte definitionem. Vim ut quis ornatus postulant, congue alterum laboramus mel an. Vis option eligendi consectetuer ad.\r\n\r\nNam eleifend constituam at, purto nemore constituam te qui. Mea te dicam maiorum, dolore gloriatur vel ne. Suas magna ea mel. Quo ad everti mollis offendit, usu quem debet persequeris ad. Eos id quando regione, alii sint elit cum ex, per in quem ponderum.\r\n\r\nIpsum vivendo dissentiunt at sed. Ex eum summo essent, pro cu tale doctus eleifend, vis partiendo simi'),
(2, 'https://images.pexels.com/photos/1204649/pexels-photo-1204649.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'Ad his oratio sadipscing disputationi', 'In tibique omittantur eam, ut cetero commodo percipit per. Vidisse salutandi duo cu. Sed ne homero vidisse, mei simul laboramus et. Eam ut persius fastidii, ex sit graece reprehendunt, nec ut aeterno consulatu gubergren.\r\n\r\nViris graece tempor eu nam, vis in doctus insolens sententiae. Has et dicit nemore aliquid. His at omnes debitis, sit sapientem maluisset ut. Ut inani constituam persequeris qui.\r\n\r\nEam tota etiam comprehensam ad. An est facer dissentiunt, eam ut solet nostro consequat. Eam dico nobis ut, duo an eleifend comprehensam. Quodsi nonumes persecuti ea sed, cu cum commodo docendi principes. Vix id mucius dictas facilisi, et deleniti iudicabit assentior sea.'),
(3, 'https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'Nam vitae interdum ligula.', ' Nunc non varius diam. Mauris gravida ullamcorper sagittis. Cras nec viverra diam, in dapibus justo. Duis at felis nunc. Nam ullamcorper vulputate est id imperdiet. Sed ac ex laoreet, pharetra nunc vel, fermentum neque. Aenean mi tellus, fermentum vel odio non, commodo finibus massa. Integer iaculis commodo sem, at tempor massa consequat ut.'),
(4, 'https://images.pexels.com/photos/7376/startup-photos.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'Duis sagittis tempor nulla in aliquam.', ' Aenean sit amet consectetur lacus. Phasellus lacinia sollicitudin ex et scelerisque. Integer nec commodo sapien, sed ultrices sapien. Nam dapibus lobortis rutrum. Sed nec lacus non urna maximus posuere. Vivamus bibendum risus in ligula gravida condimentum. Mauris hendrerit mattis malesuada. Vivamus commodo, est ut blandit ullamcorper, leo purus luctus leo, porta viverra dolor nunc id turpis. Phasellus ullamcorper egestas libero viverra vehicula. Vestibulum condimentum rhoncus lorem eu vehicula. Curabitur consequat velit lacus, a convallis nulla porta tincidunt.'),
(5, 'https://images.pexels.com/photos/7357/startup-photos.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'Proin vel tempor metus.', ' Maecenas luctus risus felis, ac lacinia magna faucibus sed. Sed fringilla tortor vitae mi pretium, eget tincidunt elit sodales. Donec eu facilisis eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quis tellus tempor, ultrices metus at, vulputate justo. Curabitur iaculis eros quis lorem placerat scelerisque. Ut facilisis, dui vel fringilla vehicula, nibh neque venenatis ligula, id fermentum odio purus at arcu. In ac posuere leo. Vestibulum velit odio, gravida quis consectetur eu, lobortis in nisi. Maecenas tempor auctor faucibus. Duis eleifend non massa in feugiat.'),
(6, 'https://images.pexels.com/photos/1106468/pexels-photo-1106468.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'Duis nulla risus', ', convallis nec ipsum quis, tincidunt tincidunt ante. Phasellus non viverra quam, eget maximus leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada bibendum placerat. Maecenas elementum finibus blandit. Cras ut ipsum ac leo vulputate elementum vitae at quam. Quisque lorem augue, sodales in tortor vel, blandit tincidunt neque. Curabitur quis nulla faucibus, vestibulum nibh et, euismod eros. Vivamus pretium nunc ac eros sollicitudin porta. Praesent lorem ipsum, lobortis vel congue id, venenatis et orci. Nam vel quam at mi convallis rutrum nec et orci. Vestibulum a tellus pharetra, aliquet lorem sit amet, porta magna.'),
(7, 'https://images.pexels.com/photos/461077/pexels-photo-461077.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', 'Cras suscipit consequat mi', ', aliquam tempus massa aliquet eget. Aliquam cursus sit amet sapien sodales dictum. Sed egestas porttitor auctor. Vivamus at porta erat. Suspendisse at nisi nulla. Sed faucibus nisi sed ipsum finibus, in aliquet magna interdum. Vivamus elementum condimentum iaculis. Suspendisse malesuada nibh enim, vel lacinia velit placerat in. Nulla tempor accumsan lobortis. Donec ullamcorper, diam vitae bibendum pretium, mauris ante fermentum libero, sed lobortis enim ante non diam.\r\n\r\nDuo cu aperiam atomorum imperdiet, mediocrem honestatis te usu. Mel mentitum accusata argumentum ne. Eu duis platonem vis. Ne duo modus zril definitionem, mel nostro sapientem mnesarchum in. Dicta vitae ad pri, labitur scriptorem consequuntur usu cu, ad dolor clita mentitum mel.'),
(8, 'https://images.pexels.com/photos/247791/pexels-photo-247791.png?auto=compress&cs=tinysrgb&h=650&w=940', 'Pellentesque vulputate sodales tellus', ', a maximus dolor tristique eu. Donec dictum, velit nec dapibus gravida, odio diam bibendum tellus, sit amet imperdiet nisi diam et risus. Curabitur porttitor elementum massa, ac sodales orci sagittis sit amet. Maecenas a blandit lorem, eu fringilla erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In sagittis dui non ante fringilla ullamcorper. Praesent convallis magna quis nisi tristique, eu consectetur enim ultrices. Mauris suscipit quam quis nibh accumsan, a tristique quam placerat. Nullam sapien lectus, sollicitudin a luctus non, consectetur sed neque. Curabitur ipsum nibh, pharetra eget vestibulum vitae, congue in dolor. Sed nec tincidunt nibh. Mauris porta suscipit egestas. Aliquam erat volutpat.'),
(9, 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'Phasellus semper tellus sit amet leo porta', ', sit amet condimentum nulla congue. Sed eget consectetur risus. Ut aliquam viverra dapibus. Sed non mollis tortor. Duis varius sem non dolor condimentum sagittis. Quisque faucibus tortor ac massa eleifend, eget porta nisl pellentesque. In hac habitasse platea dictumst. Sed nulla orci, suscipit nec rutrum ut, sollicitudin ut velit. Nam erat erat, efficitur ac nunc fringilla, ultricies tristique leo. Sed porttitor libero nunc, quis volutpat purus feugiat vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus.'),
(10, 'https://www.molndal.se/images/18.2f559acf166a856000d335f/1541666038938/181108_Campus-Molndal_Workshop_IT-foretag_12.jpg', 'Ut mel congue deleniti', 'Quo in nulla munere epicuri, eu quas ferri postulant ius. Eos democritum neglegentur definitionem ex. Nam dolor detraxit ea, pri te temporibus delicatissimi. Vidit democritum reprimique duo ut, ex cetero epicurei mea, possim vivendo forensibus ea mei.\r\n\r\nCu rebum aperiam sed, wisi minimum petentium et vix. No eos scripta intellegam, cetero democritum per ad, vim ex fuisset sadipscing. Soluta facilisi et cum, te duo deleniti splendide. Ea eam fabulas fabellas. Mel aeterno albucius nominati no, sale putant mentitum no est. Offendit delectus deterruisset sed ne.\r\n\r\nSit timeam percipitur ut, pri purto erat ei. Vix no sumo iusto, vix feugiat inermis referrentur te, et tollit dolores rationibus est. Atqui iracundia no vis, mea sapientem assentior liberavisse no. Ubique maiorum detraxit an mea. Sed ne evertitur accommodare deterruisset, cu usu ubique patrioque, accusata dissentias nec cu. Ignota vocibus eam et.\r\n\r\nMucius mentitum ad est, ne per dolore recusabo consequat. Deleniti omittantur e'),
(11, 'https://www.molndal.se/images/18.2f559acf166a856000dfb3/1540799816095/181018_Nyhet_Campus-Molndal_IT-projektledare_Kristian-Matic%20.jpg', 'Vix te brute iriure instructior', 'No qui nemore antiopam interpretaris, ut his stet habemus consetetur. Ea habeo vocent periculis nec, mel te detracto deleniti. Nominati convenire suavitate in vel, eius adolescens vel et. Sensibus periculis cu ius, simul clita honestatis nec ei. At nec iuvaret singulis necessitatibus.\r\n\r\nFeugiat conceptam deseruisse an nec, mea et mucius adipiscing deterruisset. Vix ex habeo oportere philosophia. Petentium signiferumque usu an. Id putent quidam tacimates vix, quot erat qui ea.\r\n\r\nDicit docendi consectetuer his eu, graeco pertinacia intellegebat per in, augue democritum ne sea. Tation eruditi ei sea, in euismod omittam iracundia vix. Sit vocibus honestatis te. Per tritani complectitur ne. Minim accusata repudiare ne sit.\r\n\r\nOmnis solet fuisset usu ut. An eum impetus laoreet eleifend, nec prima saperet ad. Ea usu aeterno docendi recteque. Eu erant inimicus incorrupte his, te essent persius nam. Cum feugiat perpetua at. Et quod choro aliquando ius.\r\n\r\nAd modo ullamcorper duo, cu sea nobis'),
(12, 'https://www.molndal.se/images/18.7ce83e2a1661830f2bb2461/1538724428228/Campus-Molndal_IT-projektledare_nyhet2.jpg', 'At vel meis tractatos', 'Choro moderatius intellegebat ei nec. Mel te diam facete tincidunt. Animal efficiantur at pro, usu te omnes lobortis. Putant vulputate concludaturque ex cum, solet moderatius est an, mazim exerci ne sit. Eam eu nibh aliquip, cu est sint mnesarchum persequeris. Et per veri omnes, ut ubique invidunt volutpat ius.\r\n\r\nVel cibo solum apeirian no, in probo utinam quaerendum pri. Id duo volumus atomorum recteque, utinam consul ut pro, at detraxit atomorum cotidieque eam. Est dolores scaevola ponderum ne. Usu soleat tamquam similique ex. Enim delectus consequuntur id pri.\r\n\r\nEam veniam incorrupte definitionem cu, cum amet velit indoctum id, qui no errem impedit. Mel at porro fuisset assentior, liber ubique option pro id. Eum an diam purto solet, his fabulas meliore id. Illum apeirian elaboraret mei ut, sea modus lorem minim ex. Ut velit regione qualisque vix, eos dictas facilisis voluptatibus at.\r\n\r\nNam in nonumy placerat, vix dicat docendi probatus eu. Eos in euismod feugiat, deleniti explica');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
